---
title: "CCM_san_nic"
author: "Owen Liu"
date: "May 20, 2016"
output: html_document
---

```{r setup, include=FALSE}

library(ggplot2)
library(plyr)
library(dplyr)
library(reshape2)
library(vegan)
library(rgdal)
library(multispatialCCM)

#### Data ####
#note: all raw data has a .dat
W_D <- getwd()

# benthic species density
#**************************************
benthdens.dat <- read.csv(file=paste(W_D,'/data/Benthic density raw data.csv',sep=''))
#fix dates in the datasets to be more readable by R
betterDates <-function(dat) {
  dates<-as.Date(as.character(dat$Date),format="%m/%d/%y")
  return(dates)
}
benthdens.dat$Date <- betterDates(benthdens.dat)
#**************************************

# Species Key
#*************************************
spp.key <- read.csv(file=paste(W_D,'/data/Table4_Species_sampled.csv',sep='')) # All species, all surveys
spp.key.bdens <- spp.key[spp.key$DataSet=="Benthic density",] # just benthic density surveys
# better names
spp.key.bdens$name <- c("pat","red","purp","wavy","astro","derm","halc","halr","limp","paras","pis","pyc","cys","lam","ymac","youn","eis","pter","mac")
#**************************************

# Otter data
#***********************************
ott <- read.csv(file=paste(W_D,"/data/Table2_independent_sea_otters.csv",sep=""))
ott$Date<-as.Date(ott$Date,format="%m/%d/%Y")
# Have to manually match otter counts to periods in the benthic data, and assume population statis between periods when otters weren't counted
ott.counts.west <- c(rep(0,29),rep(10,3),9,rep(13,4),18,18,rep(20,3),24,22,20,20,30,29,29,29,29,31,31,18,18,30,34,42)
ott.counts.north <- c(rep(0,29),rep(4,3),5,rep(1,9),0,1,rep(0,7),1,1,0,0,1,4,0)
ott.counts.south <- c(rep(0,32),3,rep(0,4),2,2,rep(0,3),3,6,13,13,2,2,2,2,2,5,5,19,19,2,8,6)
ott.abun.key <- data.frame(period=sort(unique(benthdens.dat$Period)),west=ott.counts.west,north=ott.counts.north,south=ott.counts.south)

# **********************************

## Create separate datasets for each site/swath combo (rows are periods, columns are species), and cast to matrices of periodxspecies
# **********************************
sites.swaths <- aggregate(list(dens=benthdens.dat$Density),by=list(station=benthdens.dat$Station,period=benthdens.dat$Period,swath=benthdens.dat$Swath,species=benthdens.dat$SpeciesCode), FUN=mean)

sit.names <- unique(sites.swaths$station)


for(i in sit.names) {
  dat.t <- subset(sites.swaths,sites.swaths$station==i) #subset of 'master' (long form) for a given site
  for(j in unique(dat.t$swath)) {
    dat.t.swath <- subset(dat.t,dat.t$swath==j)
    dat.t.swath <- acast(dat.t.swath,period~species,value.var="dens") # cast to matrix
    dat.t.swath <- as.data.frame((dat.t.swath))
    names(dat.t.swath) <- spp.key.bdens$name
    datname <- paste0("site",i,".",j)
    assign(datname,dat.t.swath) # assign raw data to variable name with site and swath (e.g. "site1.10L")
    
    # first differences (for detrending)
    dat.t.diff <- diff(data.matrix(dat.t.swath))
    dat.t.diff <- as.data.frame(dat.t.diff)
    datname <- paste0("site",i,".",j,".diff")
    assign(datname,dat.t.diff) # assign raw data to variable name with site and swath (e.g. "site1.10L")
  }
}
#*************************************
```

Convergent cross mapping of the time series.  Based on Sugihara et al. 2012 Science; and Clark et al. 2015 Ecology.

```{r CCM benthic data}
require(multispatialCCM)

# Starting with site(station) 2 (West End of SNI)
# Hellinger-transform the data
site2.10L.hel <- decostand(site2.10L,"hel")
site2.22L.hel <- decostand(site2.22L,"hel")
site2.32R.hel <- decostand(site2.32R,"hel")
site2.39L.hel <- decostand(site2.39L,"hel")
site2.45L.hel <- decostand(site2.45L,"hel")
NA.row <- as.data.frame(rep(NA,length(site2.10L.hel))) ## NAs are for linking "spatially-replicated time series" for multispatial CCM, see package and text
NA.row <- as.data.frame(t(NA.row))
names(NA.row) <- names(site2.10L)

# Bind all swaths ("replicates") together to produce the final dataset for testing
site2.all.hel <- bind_rows(site2.10L.hel,NA.row,site2.22L.hel,NA.row,site2.32R.hel,NA.row,site2.39L.hel,NA.row,site2.45L.hel)
site2.all.hel <- as.data.frame(site2.all.hel)

### First, try to find optimal E (embedding dimension) 
#***************************

maxE<-18 #Maximum E to test

# Matrix for storing output
Etest<-data.frame("E"=2:maxE,"pat"=NA,"red"=NA,"purp"=NA,"wavy"=NA,"astro"=NA,"derm"=NA,"halc"=NA,"halr"=NA,"limp"=NA,"paras"=NA,"pis"=NA,"pyc"=NA,"cys"=NA,"lam"=NA,"ymac"=NA,"youn"=NA,"eis"=NA,"pter"=NA,"mac"=NA)

# For each variable/species' timeseries, loop over potential E values and 
# calculate predictive ability rho of each process for its own dynamics
for(E in 2:maxE) {
#Uses defaults of looking forward one prediction step (predstep)
#And using time lag intervals of one time step (tau)
  for(i in names(site2.all.hel)) {
    Etest[E-1,i]<-SSR_pred_boot(A=site2.all.hel[,i], E=E, predstep=1, tau=1)$rho
  }
}

# Look at plots to find E for each variable at which predictive ability rho is maximized
matplot(2:maxE, Etest[2:length(Etest)], type="l", col=rainbow(19), lty=1:3,
xlab="E", ylab="rho", lwd=2)
.pardefault <- par(no.readonly = T)
par(xpd=T,mar=c(5,4,4,12))
legend(12.5,0.8, names(Etest[2:length(Etest)]), lty=1:3, col=rainbow(19), lwd=2, bty="n")
par(.pardefault)

## Remove NA columns (species for which there was no variation (e.g. rare species, lots of zeros))
Etest <- Etest[,colSums(is.na(Etest)) == 0]

# Graph relationships between embedding dimension and rho
Emelt <- melt(Etest,id.vars="E") # long form for plotting
ggplot(Emelt,aes(x=E,y=value)) +geom_line()+facet_wrap("variable")
# Many of the plots are relatively flat, i.e. there isn't a huge tradeoff from choosing a shorter, more parsimonious embedding dimension.

# find best E for each variable (maximum absolute value rho)
bestE <- data.frame(E=sapply(Etest[2:length(Etest)],function(x) Etest$E[abs(x)==max(abs(x))]))
bestE$rho <- sapply(Etest[2:length(Etest)],function(x) x[abs(x)==max(abs(x))])

### Now we have optimal embedding dimension for each variable

#****************************************
# Check data for nonlinear signal that is not dominated by noise
# Checks whether predictive ability of processes declines with increasing time distance
signal_purp_check <- SSR_check_signal(A=site2.all.hel$purp,E=bestE["purp","E"],predsteplist=1:18,matchSugi = 0)
plot(signal_purp_check$predatout,type="l",col="purple")

signal_red_check <- SSR_check_signal(A=site2.all.hel$red,E=bestE["red","E"],predsteplist=1:18,matchSugi = 0)
plot(signal_red_check$predatout,type="l",col="red")

signal_mac_check <- SSR_check_signal(A=site2.all.hel$mac,E=bestE["mac","E"],predsteplist=1:18,matchSugi = 0)
plot(signal_mac_check$predatout,type="l",col="darkgreen")

signal_cys_check <- SSR_check_signal(A=site2.all.hel$cys,E=bestE["cys","E"],predsteplist=1:18,matchSugi = 0)
plot(signal_cys_check$predatout,type="l",col="orange")

### a major problem in these "diagnostic plots" for some variables is the rise in predictive power with prediction interval (U-shaped graphs), suggesting cyclical patterns or a temporal trend in the data.  Try first-differencing and standardizing each timeseries to unit variance (mean 0, sd 1).
#*********************
site2.10L.st.diff <- decostand(site2.10L.diff,method="standardize")
site2.22L.st.diff <- decostand(site2.22L.diff,method="standardize")
site2.32R.st.diff <- decostand(site2.32R.diff,method="standardize")
site2.39L.st.diff <- decostand(site2.39L.diff,method="standardize")
site2.45L.st.diff <- decostand(site2.45L.diff,method="standardize")
NA.row <- as.data.frame(rep(NA,length(site2.10L.st.diff))) ## NAs are for linking "spatially-replicated time series" for multispatial CCM, see package and text
NA.row <- as.data.frame(t(NA.row))
names(NA.row) <- names(site2.10L.st.diff)

# Bind all swaths ("replicates") together to produce the final dataset for testing
site2.all.st.diff <- bind_rows(site2.10L.st.diff,NA.row,site2.22L.st.diff,NA.row,site2.32R.st.diff,NA.row,site2.39L.st.diff,NA.row,site2.45L.st.diff)
site2.all.st.diff <- as.data.frame(site2.all.st.diff)

## Embedding dimension
Etest.diff<-data.frame("E"=2:maxE,"pat"=NA,"red"=NA,"purp"=NA,"wavy"=NA,"astro"=NA,"derm"=NA,"halc"=NA,"halr"=NA,"limp"=NA,"paras"=NA,"pis"=NA,"pyc"=NA,"cys"=NA,"lam"=NA,"ymac"=NA,"youn"=NA,"eis"=NA,"pter"=NA,"mac"=NA)

# For each variable/species' timeseries, loop over potential E values and 
# calculate predictive ability rho of each process for its own dynamics
for(E in 2:maxE) {
#Uses defaults of looking forward one prediction step (predstep)
#And using time lag intervals of one time step (tau)
  for(i in names(site2.all.st.diff)) {
    Etest.diff[E-1,i]<-SSR_pred_boot(A=site2.all.st.diff[,i], E=E, predstep=1, tau=1)$rho
  }
}

## Remove NA columns (species for which there was no variation (e.g. rare species, lots of zeros))
Etest.diff <- Etest.diff[,colSums(is.na(Etest.diff)) == 0]

# Graph relationships between embedding dimension and rho
Emelt.diff <- melt(Etest.diff,id.vars="E") # long form for plotting
ggplot(Emelt.diff,aes(x=E,y=value)) +geom_line()+facet_wrap("variable")

# find best E for each variable (maximum absolute value rho)
bestE.diff <- data.frame(E=sapply(Etest.diff[2:length(Etest.diff)],function(x) Etest.diff$E[abs(x)==max(abs(x))]))
bestE.diff$rho <- sapply(Etest.diff[2:length(Etest.diff)],function(x) x[abs(x)==max(abs(x))])

# Checks whether predictive ability of processes declines with increasing time distance
signal_purp_check <- SSR_check_signal(A=site2.all.st.diff$purp,E=bestE.diff["purp","E"],predsteplist=1:18,matchSugi = 0)
plot(signal_purp_check$predatout,type="l",col="purple")

signal_red_check <- SSR_check_signal(A=site2.all.st.diff$red,E=bestE.diff["red","E"],predsteplist=1:18,matchSugi = 0)
plot(signal_red_check$predatout,type="l",col="red")

signal_mac_check <- SSR_check_signal(A=site2.all.st.diff$mac,E=bestE.diff["mac","E"],predsteplist=1:18,matchSugi = 0)
plot(signal_mac_check$predatout,type="l",col="darkgreen")

signal_cys_check <- SSR_check_signal(A=site2.all.st.diff$cys,E=bestE.diff["cys","E"],predsteplist=1:18,matchSugi = 0)
plot(signal_cys_check$predatout,type="l",col="orange")
#******************************

```

Do red and purple urchins drive each other at the West End?

```{r red vs. purple}
#Run the CCM test
#E_A and E_B are the embedding dimensions for A and B.
#tau is the length of time steps used (default is 1)
#iterations is the number of bootsrap iterations (default 100)
# Does red "cause" purp?

# For both species' timeseries, best embedding dimension was 5
E_urch <- 5

# Test for "red causing purple"
CCM_boot_red<-CCM_boot(A=site2.all.hel$red, B=site2.all.hel$purp, E=5, tau=1, iterations=100)
# quick plot of result
plot(CCM_boot_red$Lobs,CCM_boot_red$rho,type="l",col="red",main="Library length vs. predictive ability",xlab="Library length (L)",ylab="Pearson corr coeff")

# Does purp "cause" red?
CCM_boot_purp<-CCM_boot(A=site2.all.hel$purp, B=site2.all.hel$red, E=5, tau=1, iterations=100)
lines(CCM_boot_purp$Lobs,CCM_boot_purp$rho,type="l",col="purple")

#Test for significant causal signal
#See R function for details
(CCM_significance_test<-ccmtest(CCM_boot_red,
CCM_boot_purp))

```

Red urchins and macrocystis

```{r red and mac CCM}
# Test for "red causing mac"
CCM_red_cause_mac<-CCM_boot(A=site2.all.hel$red, B=site2.all.hel$mac, E=5, tau=1, iterations=100)
# quick plot of result
plot(CCM_red_cause_mac$Lobs,CCM_red_cause_mac$rho,type="l",col="red",main="Library length vs. predictive ability",xlab="Library length (L)",ylab="Pearson corr coeff",ylim=c(0,0.7))

# Does mac "cause" red?
CCM_mac_cause_red<-CCM_boot(A=site2.all.hel$purp, B=site2.all.hel$red, E=5, tau=1, iterations=100)
lines(CCM_mac_cause_red$Lobs,CCM_mac_cause_red$rho,type="l",col="green")

# in ggplot
red.mac <- data.frame(L=CCM_mac_cause_red$Lobs,rho.1=CCM_red_cause_mac$rho,rho.2=CCM_mac_cause_red$rho,sd.1=CCM_red_cause_mac$sdevrho, sd.2=CCM_mac_cause_red$sdevrho)
red.mac$upper.1 <- red.mac$rho.1+red.mac$sd.1
red.mac$lower.1 <- red.mac$rho.1-red.mac$sd.1
red.mac$upper.2 <- red.mac$rho.2+red.mac$sd.2
red.mac$lower.2 <- red.mac$rho.2-red.mac$sd.2

cols <- c("Red causes mac"="red","Mac causes red"="green")
ggplot(red.mac) + geom_ribbon(aes(x=L,ymin=lower.1,ymax=upper.1),fill="grey70")+
  geom_ribbon(aes(x=L,ymin=lower.2,ymax=upper.2),fill="grey70")+
  geom_line(aes(x=L,y=rho.1,col="Red causes mac")) +
  geom_line(aes(x=L,y=rho.2,col="Mac causes red")) +
  labs(title="CCM, Red Urchins and Macrocystis, Site 2",x="Library length (L)",y="Pearson correlation coefficient +/- 1 SD")+
  scale_color_manual(values=cols)
  

#Test for significant causal signal
#See R function for details
(CCM_significance_test<-ccmtest(CCM_red_cause_mac,
CCM_mac_cause_red))

### with first-differenced, standardized data
# Test for "red causing mac" (E=13 from previous analysis)
CCM_red_cause_mac<-CCM_boot(A=site2.all.st.diff$red, B=site2.all.st.diff$mac, E=13, tau=1, iterations=100)
# quick plot of result
plot(CCM_red_cause_mac$Lobs,CCM_red_cause_mac$rho,type="l",col="red",main="Library length vs. predictive ability",xlab="Library length (L)",ylab="Pearson corr coeff",ylim=c(0,0.7))

# Does mac "cause" red? (E=4)
CCM_mac_cause_red<-CCM_boot(A=site2.all.st.diff$purp, B=site2.all.st.diff$red, E=4, tau=1, iterations=100)
lines(CCM_mac_cause_red$Lobs,CCM_mac_cause_red$rho,type="l",col="green")

# in ggplot
red.mac <- data.frame(L1=CCM_red_cause_mac$Lobs,L2=CCM_mac_cause_red$Lobs,rho.1=CCM_red_cause_mac$rho,rho.2=CCM_mac_cause_red$rho,sd.1=CCM_red_cause_mac$sdevrho, sd.2=CCM_mac_cause_red$sdevrho)
red.mac$upper.1 <- red.mac$rho.1+red.mac$sd.1
red.mac$lower.1 <- red.mac$rho.1-red.mac$sd.1
red.mac$upper.2 <- red.mac$rho.2+red.mac$sd.2
red.mac$lower.2 <- red.mac$rho.2-red.mac$sd.2

cols <- c("Red causes mac"="red","Mac causes red"="green")
ggplot(red.mac) + geom_ribbon(aes(x=L,ymin=lower.1,ymax=upper.1),fill="grey70")+
  geom_ribbon(aes(x=L,ymin=lower.2,ymax=upper.2),fill="grey70")+
  geom_line(aes(x=L,y=rho.1,col="Red causes mac")) +
  geom_line(aes(x=L,y=rho.2,col="Mac causes red")) +
  labs(title="CCM, Red Urchins and Macrocystis, Site 2",x="Library length (L)",y="Pearson correlation coefficient +/- 1 SD")+
  scale_color_manual(values=cols)
  

#Test for significant causal signal
#See R function for details
(CCM_significance_test<-ccmtest(CCM_red_cause_mac,
CCM_mac_cause_red))

## FAILLLLLL
```

