---
title: "El Nino and CCM"
author: "Owen Liu"
date: "May 31, 2016"
output: html_document
---

```{r setup, include=FALSE}

library(ggplot2)
library(plyr)
library(dplyr)
library(reshape2)
library(vegan)
library(rgdal)
library(multispatialCCM)
library(tseries)
library(lubridate)

#### Data ####
#note: all raw data has a .dat
W_D <- getwd()

# benthic species density
#**************************************
benthdens.dat <- read.csv(file=paste(W_D,'/data/Benthic density raw data.csv',sep=''))
#fix dates in the datasets to be more readable by R
betterDates <-function(dat) {
  dates<-as.Date(as.character(dat$Date),format="%m/%d/%y")
  return(dates)
}
benthdens.dat$Date <- betterDates(benthdens.dat)
#**************************************

# benthic species cover
#**************************************
benthcover.dat <- read.csv(file=paste(W_D,'/data/Benthic cover raw data.csv',sep=''))
#fix dates in the datasets to be more readable by R
benthcover.dat$Date <- betterDates(benthcover.dat)
#**************************************

# benthic fish density
# *************************************
fishdens.dat <- read.csv(file=paste(W_D,'/data/Benthic fish density raw data.csv',sep=''))
#fix dates in the datasets to be more readable by R
fishdens.dat$Date <- betterDates(fishdens.dat)
# *************************************

# midwater fish density
# *************************************
midwaterfish.dat <-  read.csv(file=paste(W_D,'/data/Midwater fish density raw data.csv',sep=''))
#fix dates in the datasets to be more readable by R
midwaterfish.dat$Date <- betterDates(midwaterfish.dat)
# *************************************

# Species Key
#*************************************
spp.key.full <- read.csv(file=paste(W_D,'/data/Table4_Species_sampled.csv',sep='')) # All species, all surveys
spp.key.bdens <- spp.key.full[spp.key.full$DataSet=="Benthic density",] # just benthic density surveys
# better names
spp.key.bdens$name <- c("pat","red","purp","wavy","astro","derm","halc","halr","limp","paras","pis","pyc","cys","lam","ymac","youn","eis","pter","mac")
#**************************************

# Otter data
#***********************************
ott <- read.csv(file=paste(W_D,"/data/Table2_independent_sea_otters.csv",sep=""))
ott$Date<-as.Date(ott$Date,format="%m/%d/%Y")
# Have to manually match otter counts to periods in the benthic data, and assume population statis between periods when otters weren't counted
ott.counts.west <- c(rep(0,29),rep(10,3),9,rep(13,4),18,18,rep(20,3),24,22,20,20,30,29,29,29,29,31,31,18,18,30,34,42)
ott.counts.north <- c(rep(0,29),rep(4,3),5,rep(1,9),0,1,rep(0,7),1,1,0,0,1,4,0)
ott.counts.south <- c(rep(0,32),3,rep(0,4),2,2,rep(0,3),3,6,13,13,2,2,2,2,2,5,5,19,19,2,8,6)
ott.abun.key <- data.frame(period=sort(unique(benthdens.dat$Period)),west=ott.counts.west,north=ott.counts.north,south=ott.counts.south)
# **********************************

```


```{r benthic density dataset splits}
## Create separate datasets for each site/swath combo (rows are periods, columns are species), and cast to matrices of periodxspecies
# **********************************
sites.swaths <- aggregate(list(dens=benthdens.dat$Density),by=list(station=benthdens.dat$Station,period=benthdens.dat$Period,swath=benthdens.dat$Swath,species=benthdens.dat$SpeciesCode), FUN=mean)

sit.names <- unique(sites.swaths$station)


for(i in sit.names) {
  dat.t <- subset(sites.swaths,sites.swaths$station==i) #subset of 'master' (long form) for a given site
  for(j in unique(dat.t$swath)) {
    dat.t.swath <- subset(dat.t,dat.t$swath==j)
    dat.t.swath <- acast(dat.t.swath,period~species,value.var="dens") # cast to matrix
    dat.t.swath <- as.data.frame((dat.t.swath))
    names(dat.t.swath) <- spp.key.bdens$name
    datname <- paste0("site",i,".",j)
    assign(datname,dat.t.swath) # assign raw data to variable name with site and swath (e.g. "site1.10L")
    
    # first differences (for detrending)
    dat.t.diff <- diff(data.matrix(dat.t.swath))
    dat.t.diff <- as.data.frame(dat.t.diff)
    datname <- paste0("site",i,".",j,".diff")
    assign(datname,dat.t.diff) # assign raw data to variable name with site and swath (e.g. "site1.10L")
  }
}
#*************************************
```


### Adding an environmental signal-- what about El Nino?

```{r el nino}
en <- read.csv(file=paste0(W_D,"/data/elnino_sst.csv"))
en.melt<-melt(en,id.vars="Year")%>%arrange(Year,variable)%>%mutate(month = as.numeric(variable))
en.ts <- ts(en.melt$value,start=c(1979),frequency = 12)
plot(en.ts,main="El Nino Index, SST Anomaly 3 month running average",xlab="Year",ylab="SST Anomaly")
abline(h=0,lty=2)

## Have to match periods in the benthic data to El Nino values
en.per.match <- data.frame(period=1:63,date=NA,ssta=NA)
# find first date in the benthic dataset corresponding to each period
en.per.match$date <- benthdens.dat$Date[match(1:63,benthdens.dat$Period)]
# pull years and months from the date, and join el nino indices for those year/months
require(lubridate)
en.per.match$year <- year(en.per.match$date)
en.per.match$month <- month(en.per.match$date)
en.per.match$ssta <- left_join(en.per.match,en.melt,by=c("year"="Year","month"="month"))$value

# now we have El Nino index matched to periods from the surveys, like so:
ggplot(en.per.match,aes(x=period,y=ssta))+geom_line()+
  xlab("Period")+ylab("SST anomaly")+ggtitle("Oceanic Nino Index over SNI Survey Periods")+
  geom_hline(yintercept=0,linetype=2)


## fish key (2 fewer periods)
en.per.match.fish <- filter(en.per.match,period>2)

```

CCM ENSO and macrocystis?

```{r CCM, enso macrocystis}

# Add ENSO SSTA data to site 4 data as a column
enso.key <- data.frame(period=as.integer(row.names(site4.10R)))
enso.key <- left_join(enso.key,en.per.match)
enso.key.diff <- data.frame(period=as.integer(row.names(site4.10R.diff)))
enso.key.diff <- left_join(enso.key.diff,en.per.match)
ssta.site4 <- enso.key$ssta
ssta.site4.diff <- enso.key.diff$ssta

# Linking the spatial replicates together (using FIRST DIFFERENCED DATA)
NA.row <- as.data.frame(rep(NA,length(site4.10R.diff))) ## NAs are for linking "spatially-replicated time series" for multispatial CCM, see package and text
NA.row <- as.data.frame(t(NA.row))
names(NA.row) <- names(site4.10R.diff)

# Bind all swaths ("replicates") together to produce the final dataset for testing (raw and first differenced)
site4.all.diff <- bind_rows(site4.10R.diff,NA.row,site4.22L.diff,NA.row,site4.32L.diff,NA.row,site4.39L.diff,NA.row,site4.45L.diff)
site4.all.diff <- as.data.frame(site4.all.diff)
site4.all <- bind_rows(site4.10R,NA.row,site4.22L,NA.row,site4.32L,NA.row,site4.39L,NA.row,site4.45L)
site4.all <- as.data.frame(site4.all)
# *****************************


# Determine E (best embedding dimension)
# *****************************
maxE=12
# Matrix for storing output
Etest<-data.frame("E"=2:maxE,"pat"=NA,"red"=NA,"purp"=NA,"wavy"=NA,"astro"=NA,"derm"=NA,"halc"=NA,"halr"=NA,"limp"=NA,"paras"=NA,"pis"=NA,"pyc"=NA,"cys"=NA,"lam"=NA,"ymac"=NA,"youn"=NA,"eis"=NA,"pter"=NA,"mac"=NA)

# For each variable/species' timeseries, loop over potential E values and 
# calculate predictive ability rho of each process for its own dynamics
for(E in 2:maxE) {
#Uses defaults of looking forward one prediction step (predstep)
#And using time lag intervals of one time step (tau)
  for(i in names(site4.all.diff)) {
    Etest[E-1,i]<-SSR_pred_boot(A=site4.all.diff[,i], E=E, predstep=1, tau=1)$rho
  }
}

## Remove NA columns (species for which there was no variation (e.g. rare species, lots of zeros))
Etest <- Etest[,colSums(is.na(Etest)) == 0]

# Graph relationships between embedding dimension and rho
Emelt <- melt(Etest,id.vars="E") # long form for plotting
ggplot(Emelt,aes(x=E,y=value)) +geom_line()+facet_wrap("variable")
# Many of the plots are relatively flat, i.e. there isn't a huge tradeoff from choosing a shorter, more parsimonious embedding dimension.

Etest.enso <- data.frame(E=2:maxE,rho=NA)
for(E in 2:maxE) Etest.enso$rho[E-1] <-SSR_pred_boot(A=ssta.site4.diff, E=E, predstep=1, tau=1)$rho

# for now, we choose:
mac.E <- 6
enso.E <- 2
# ****************************************

# Check data for nonlinear signal that is not dominated by noise
# Checks whether predictive ability of processes declines with increasing time distance
#*********************************
mac_signal <- SSR_check_signal(A=site4.all.diff$mac,E=mac.E,predsteplist=1:25,matchSugi = 0)
plot(mac_signal$predatout,type="l",col="darkgreen",lwd=2)

enso_signal<- SSR_check_signal(A=ssta.site4.diff,E=enso.E,predsteplist=1:18,matchSugi = 0)
plot(enso_signal$predatout,type="l",col="red",lwd=2)
# Looks okay!
#**********************************

# Run the CCM algorithm using the embedding dimensions for the variables chosen above
# Run it both ways (check for causal signal both ways)
## hypothesis is that enso signal should "drive" macrocystis, but NOT the other way around
# ******************************

# Test for "mac causing enso"
CCM_mac_enso<-CCM_boot(A=site4.all.diff$mac, B=ssta.site4.diff, E=mac.E, tau=1, iterations=100)

# quick plot of result
plot(CCM_mac_enso$Lobs,CCM_mac_enso$rho,type="l",col="red",main="Library length vs. predictive ability",xlab="Library length (L)",ylab="Pearson corr coeff")

# Test for "enso causing mac"
CCM_enso_mac<-CCM_boot(A=ssta.site4.diff, B=site4.all.diff$mac, E=enso.E, tau=1, iterations=100)
plot(CCM_enso_mac$Lobs,CCM_enso_mac$rho,type="l",col="purple",main="Library length vs. predictive ability",xlab="Library length (L)",ylab="Pearson corr coeff")

#Test for significant causal signal
#See R function for details
(CCM_significance_test<-ccmtest(CCM_mac_enso, CCM_enso_mac))

```


CCM eisenia and enso

```{r CCM, enso eis}

# test E for non diff data
maxE=12
# Matrix for storing output
Etest2<-data.frame("E"=2:maxE,"pat"=NA,"red"=NA,"purp"=NA,"wavy"=NA,"astro"=NA,"derm"=NA,"halc"=NA,"halr"=NA,"limp"=NA,"paras"=NA,"pis"=NA,"pyc"=NA,"cys"=NA,"lam"=NA,"ymac"=NA,"youn"=NA,"eis"=NA,"pter"=NA,"mac"=NA)

for(E in 2:maxE) {
#Uses defaults of looking forward one prediction step (predstep)
#And using time lag intervals of one time step (tau)
  for(i in names(site4.all)) {
    Etest2[E-1,i]<-SSR_pred_boot(A=site4.all[,i], E=E, predstep=1, tau=1)$rho
  }
}

# Graph relationships between embedding dimension and rho
Emelt2 <- melt(Etest2,id.vars="E") # long form for plotting
ggplot(Emelt2,aes(x=E,y=value)) +geom_line()+facet_wrap("variable")


# for now, we choose:
eis.E <- 3
enso.E <- 4
# ****************************************

# Check data for nonlinear signal that is not dominated by noise
# Checks whether predictive ability of processes declines with increasing time distance
#*********************************
eis_signal <- SSR_check_signal(A=site4.all$eis,E=eis.E,predsteplist=1:25,matchSugi = 0)
plot(eis_signal$predatout,type="l",col="darkgreen",lwd=2)

enso_signal<- SSR_check_signal(A=ssta.site4,E=enso.E,predsteplist=1:18,matchSugi = 0)
plot(enso_signal$predatout,type="l",col="red",lwd=2)
# Looks okay!
#**********************************

# Run the CCM algorithm using the embedding dimensions for the variables chosen above
# Run it both ways (check for causal signal both ways)
## hypothesis is that enso signal should "drive" eisrocystis, but NOT the other way around
# ******************************

# Test for "eis causing enso"
CCM_eis_enso<-CCM_boot(A=site4.all$eis, B=ssta.site4, E=eis.E, tau=1, iterations=100)

# quick plot of result
plot(CCM_eis_enso$Lobs,CCM_eis_enso$rho,type="l",col="red",main="Library length vs. predictive ability",xlab="Library length (L)",ylab="Pearson corr coeff")

# Test for "enso causing eis"
CCM_enso_eis<-CCM_boot(A=ssta.site4, B=site4.all$eis, E=enso.E, tau=1, iterations=100)
plot(CCM_enso_eis$Lobs,CCM_enso_eis$rho,type="l",col="purple",main="Library length vs. predictive ability",xlab="Library length (L)",ylab="Pearson corr coeff")

#Test for significant causal signal
#See R function for details
(CCM_significance_test<-ccmtest(CCM_eis_enso, CCM_enso_eis))

```